Portal.Web/Controllers/UserAdminController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Portal.Core.Service.Company;
using Portal.Data.Identity.Contracts;
using Portal.Data.Identity.Models;
using Portal.Dto.Dtos.Company;
using Portal.Web.Models;

namespace Portal.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        private readonly IApplicationRoleManager _roleManager;
        private readonly IApplicationUserManager _userManager;
        private readonly ICompanyGroupService _companyGroupService;
        public UsersAdminController(IApplicationUserManager userManager,
                                    IApplicationRoleManager roleManager, ICompanyGroupService companyGroupService)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _companyGroupService = companyGroupService;
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await _roleManager.GetAllCustomRolesAsync().ConfigureAwait(false), "Name", "Name");
            ViewBag.CompanyGroups = new SelectList((await _companyGroupService.GetAllGroupsAsync().ConfigureAwait(false)).Value, "Id", "Title");

            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, Guid selectedCompanyGroup, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await _userManager.CreateAsync(user, userViewModel.Password).ConfigureAwait(false);

                //Add User to the selected Roles
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await _userManager.AddToRolesAsync(user.Id, selectedRoles).ConfigureAwait(false);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await _roleManager.GetAllCustomRolesAsync().ConfigureAwait(false), "Name", "Name");
                            ViewBag.CompanyGroups = new SelectList((await _companyGroupService.GetAllGroupsAsync().ConfigureAwait(false)).Value, "Id", "Title");
                            return View();
                        }
                    }

                    _userManager.AddToCompanyGroup(user.Id, selectedCompanyGroup);
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(await _roleManager.GetAllCustomRolesAsync().ConfigureAwait(false), "Name", "Name");
                    ViewBag.CompanyGroups = new SelectList((await _companyGroupService.GetAllGroupsAsync().ConfigureAwait(false)).Value, "Id", "Title");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(await _roleManager.GetAllCustomRolesAsync().ConfigureAwait(false), "Name", "Name");
            ViewBag.CompanyGroups = new SelectList((await _companyGroupService.GetAllGroupsAsync().ConfigureAwait(false)).Value, "Id", "Title");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id.Value).ConfigureAwait(false);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await _userManager.FindByIdAsync(id.Value).ConfigureAwait(false);
                if (user == null)
                {
                    return HttpNotFound();
                }

                var result = await _userManager.DeleteAsync(user).ConfigureAwait(false);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id.Value).ConfigureAwait(false);

            ViewBag.RoleNames = await _userManager.GetRolesAsync(user.Id).ConfigureAwait(false);

            return View(user);
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id.Value).ConfigureAwait(false);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user.Id).ConfigureAwait(false);
            var allCompanyGroups = await _companyGroupService.GetAllGroupsAsync();
            return View(new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = (await _roleManager.GetAllCustomRolesAsync().ConfigureAwait(false)).Select(x => new SelectListItem
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                }),
                CompanyGroups = allCompanyGroups.Value.Select(x => new SelectListItem
                {
                    Selected = user.CompanyGroup?.Id == x.Id,
                    Text = x.Title,
                    Value = x.Id.ToString()
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, Guid selectedCompanyGroup, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(editUser.Id).ConfigureAwait(false);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await _userManager.GetRolesAsync(user.Id).ConfigureAwait(false);

                selectedRole = selectedRole ?? new string[] { };

                var result = await _userManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray()).ConfigureAwait(false);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }


                _userManager.AddToCompanyGroup(user.Id, selectedCompanyGroup);

                await _userManager.UpdateSecurityStampAsync(user.Id).ConfigureAwait(true);

                result = await _userManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray()).ConfigureAwait(false);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                await _userManager.UpdateSecurityStampAsync(user.Id).ConfigureAwait(false);

                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index()
        {
            return View(await _userManager.GetAllUsersAsync().ConfigureAwait(false));
        }


        public ActionResult AdminUsers()
        {
            return View(_roleManager.GetApplicationUsersInRole("Admin"));
        }
    }
}

Portal.Web/Views/UsersAdmin/AdminUsers.cshtml
@model IList<Portal.Data.Identity.Models.ApplicationUser>

@{
    ViewBag.Title = "Admins";
}

<h2>Admins of the system</h2>


<table class="table table-striped table-hover table-bordered table-condensed">
    <tr>
        <th>
            Name
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

Portal.Web/Views/UsersAdmin/Create.cshtml
@using Portal.Dto.Dtos.Company
@model Portal.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        @Html.Label("گروه صنعت", new { @class = "control-label col-md-2" })
        <span class=" col-md-10">
            <select name="SelectedCompanyGroup" class="form-control">
                @foreach (var item in (SelectList)ViewBag.CompanyGroups)
                {
                    <option @(item.Selected?"selected":"") value="@item.Value">@item.Text</option>
                }
            </select>
        </span>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Portal.Web/Views/UsersAdmin/Delete.cshtml
@model Portal.Data.Identity.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete.</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <h4>User.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Portal.Web/Views/UsersAdmin/Details.cshtml
@model Portal.Data.Identity.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details.</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.CompanyGroup.Title)
        </dd>
    </dl>
</div>
<h4>List of roles for this user</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>No roles found for this user.</p>
}

<table class="table table-striped table-hover table-bordered table-condensed">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Portal.Web/Views/UsersAdmin/Edit.cshtml
@model Portal.Web.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit.</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit User Form.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
               @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Roles", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" })
                }
            </span>
        </div>
        <div class="form-group">
            @Html.Label("گروه صنعت", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                <select name="SelectedCompanyGroup" class="form-control">
                    @foreach (var item in Model.CompanyGroups)
                    {
                        <option @(item.Selected?"selected":"") value="@item.Value">@item.Text</option>
                    }
                </select>
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Portal.Web/Views/UsersAdmin/Index.cshtml
@model IEnumerable<Portal.Data.Identity.Models.ApplicationUser>

@{
    ViewBag.Title = "لیست کاربران";
}

<h2>@ViewBag.Title</h2>
    <div class="col-md-12">
        <p>
            @Html.ActionLink("افزودن جدید", "Create") | @Html.ActionLink("Sys. Admins", "AdminUsers")
        </p>
        <table class="table table-striped table-hover table-bordered table-condensed">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>